---
# Variables to use specific to localhost (for working with APIs)
all:
  hosts:
    localhost:
      # Since there are multiple physical groups of systems I specify
      # a grouping of equipment to use for naming the nPod. This is unique
      # per inventory.
      demopod: "all"
      # How to wait (in minutes) for hosts to boot after nPod creation
      wait_hosts: 3
      # Netmask for data ports on Medusa cards (TME=24; Demopods=28)
      netmask_bits: 24

# Physical server inventory
servers:
  hosts:
    # HPE
    server-05.tme.nebulon.com:
      spu_serial: 0123F7A8D51D48C819
      spu_address: 10.100.29.114
    server-06.tme.nebulon.com:
      spu_serial: 01238F123073C87119
      spu_address: 10.100.29.115
    server-07.tme.nebulon.com:
      spu_serial: 0123F5132F06C5C5EE
      spu_address: 10.100.29.116
    server-08.tme.nebulon.com:
      spu_serial: 0123237A9F163BAD19
      spu_address: 10.100.29.113
    # Lenovo
    server-09.tme.nebulon.com:
      spu_serial: 012386435A39449519
      spu_address: 10.100.29.117
    server-10.tme.nebulon.com:
      spu_serial: 01231C5BA68435FC19
      spu_address: 10.100.29.118
    server-11.tme.nebulon.com:
      spu_serial: 01234C1DDA95332EEE
      spu_address: 10.100.29.119
    server-12.tme.nebulon.com:
      spu_serial: 01236AE13059FD35EE
      spu_address: 10.100.29.120
  children:
    hpe_servers:
      hosts:
        server-05.tme.nebulon.com:
          spu_serial: 0123F7A8D51D48C819
          spu_address: 10.100.29.114
        server-06.tme.nebulon.com:
          spu_serial: 01238F123073C87119
          spu_address: 10.100.29.115
        server-07.tme.nebulon.com:
          spu_serial: 0123F5132F06C5C5EE
          spu_address: 10.100.29.116
        server-08.tme.nebulon.com:
          spu_serial: 0123237A9F163BAD19
          spu_address: 10.100.29.113
    lenovo_servers:
      hosts:
        server-09.tme.nebulon.com:
          spu_serial: 012386435A39449519
          spu_address: 10.100.29.117
        server-10.tme.nebulon.com:
          spu_serial: 01231C5BA68435FC19
          spu_address: 10.100.29.118
        server-11.tme.nebulon.com:
          spu_serial: 01234C1DDA95332EEE
          spu_address: 10.100.29.119
        server-12.tme.nebulon.com:
          spu_serial: 01236AE13059FD35EE
          spu_address: 10.100.29.120

spus:
  hosts:
    # HPE
    medusa-b045e.tme.nebulon.com:
    medusa-b042a.tme.nebulon.com:
    medusa-a911.tme.nebulon.com:
    medusa-b045c.tme.nebulon.com:
    # Lenovo
    medusa-b0421.tme.nebulon.com:
    medusa-b0428.tme.nebulon.com:
    medusa-a912.tme.nebulon.com:
    medusa-a915.tme.nebulon.com:
  children:
    hpe_spus:
      hosts:
        medusa-b045e.tme.nebulon.com:
        medusa-b042a.tme.nebulon.com:
        medusa-a911.tme.nebulon.com:
        medusa-b045c.tme.nebulon.com:
    lenovo_spus:
      hosts:
        medusa-b0421.tme.nebulon.com:
        medusa-b0428.tme.nebulon.com:
        medusa-a912.tme.nebulon.com:
        medusa-a915.tme.nebulon.com:

hpe_ilom:
  hosts:
    server-05-lom.tme.nebulon.com:
      baseuri: server-05-lom.tme.nebulon.com
    server-06-lom.tme.nebulon.com:
      baseuri: server-06-lom.tme.nebulon.com
    server-07-lom.tme.nebulon.com:
      baseuri: server-07-lom.tme.nebulon.com
    server-08-lom.tme.nebulon.com:
      baseuri: server-08-lom.tme.nebulon.com
  vars:
    username: Administrator
    password: "{{ vault_ilom_password }}"
    # Local directory where all results are placed
    rootdir: ../../../results

    # Shorter name for inventory_hostname
    # Refers to the logical inventory hostname (example: redfish1)
    host: "{{ inventory_hostname }}"

lenovo_ilom:
  hosts:
    server-09-lom.tme.nebulon.com:
      baseuri: server-09-lom.tme.nebulon.com
    server-10-lom.tme.nebulon.com:
      baseuri: server-10-lom.tme.nebulon.com
    server-11-lom.tme.nebulon.com:
      baseuri: server-11-lom.tme.nebulon.com
    server-12-lom.tme.nebulon.com:
      baseuri: server-12-lom.tme.nebulon.com
  vars:
    username: Administrator
    password: "{{ vault_ilom_password }}"
    # Local directory where all results are placed
    rootdir: ../../../results

    # Shorter name for inventory_hostname
    # Refers to the logical inventory hostname (example: redfish1)
    host: "{{ inventory_hostname }}"