---
# This playbook does a full end-to-end installation of a virtualized K8s deployment
# including the VMware CSI driver and Kube-Prometheus.

# Example Invocation:
# ansible-playbook -i inventory/lenovo-brb.yml playbooks/ansible-playbook-k8s-virtual/deploy_k8s_vms.yml
# ansible-playbook -i inventory/hpe-brb.yml playbooks/ansible-playbook-k8s-virtual/deploy_k8s_vms.yml

# ===========================================================================
# Deploy VMs
# ===========================================================================
- name: Deploy VMs
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  module_defaults:
    group/vmware:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vault_vcenter_password }}'
      validate_certs: false
  tags: play_deploy_vms

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - { role: jedimt.deploy_vms,
        ansible_password: "{{ vault_ansible_password }}",
        # vCenter datacenter to deploy VMs to
        vcenter_datacenter: 'SC0',

        # Folder where the VMs should be deployed
        vcenter_folder: '/{{ vcenter_datacenter }}/vm/Kubernetes',

        # vCenter cluster to use
        vcenter_cluster: 'AppFactory',

        # vCenter IP or FQDN
        vcenter_hostname: 'devvcsa.tme.nebulon.com',

        # The VM network name to attach to the VM
        guest_network: 'dvs_appfactory-vmnetwork',

        # Netmask to use for guest IP address (defined in inventory by default)
        guest_netmask: '255.255.252.0',

        # Guest IPv4 gateway
        guest_gateway: '10.100.24.1',

        # DNS server
        guest_dns_server: '10.100.24.11',

        # Domain search
        guest_domain_name: 'tme.nebulon.com',

        # Guest template to clone for VMs
        guest_template: 'ubuntu20.04.4_local',

        # Vault credentials
        vcenter_username: "{{ vault_vcenter_username }}",
        vcenter_password: "{{ vault_vcenter_password }}"
    }

# ===========================================================================
# Customize VMs
# ===========================================================================
- name: Customize deployed VMs
  hosts: servers
  gather_facts: false
  tags: play_customize_vms

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    # If passwordless SSH not set up, use ansible_password to authenticate
    - { role: jedimt.customize_vms,
        ansible_password: "{{ vault_ansible_password }}"
    }

# ===========================================================================
# Copy SSH keys to target hosts for passwordless authentication
# ===========================================================================
- name: Copy pubkeys to target hosts
  hosts: servers
  gather_facts: false
  tags: play_ssh_setup

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - jedimt.authorized_keys

# ===========================================================================
# Update Ansible controller SSH keys
# ===========================================================================
- name: Update SSH keys for Ansible controller known_hosts
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags: play_ssh_sync

  roles:
    - jedimt.ssh

# ===========================================================================
# Disable APT automatic updates/upgrades
# ===========================================================================
- name: Disable APT updates and upgrades
  hosts: servers
  gather_facts: false

  roles:
    - jedimt.apt

# ===========================================================================
# Install HAProxy on a VM
# ===========================================================================
- name: Install HAProxy on VM
  hosts: haproxy
  gather_facts: true
  tags: play_haproxy

  roles:
    - jedimt.haproxy


# ===========================================================================
# Kubernetes pre-install tasks
# ===========================================================================
- name: Kubernetes pre-install tasks
  hosts: servers
  tags: play_k8s_prep

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - jedimt.kubernetes_prep

# ===========================================================================
# Create Kubernetes cluster
# ===========================================================================
- name: Create Kubernetes cluster
  hosts: k8s_master
  tags: play_create_k8s_cluster

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - jedimt.kubernetes_create_cluster

# This play will only fire when multiple control nodes are to be configured
- name: Join additional control nodes to K8s cluster
  hosts: k8s_control
  tags: play_k8s_control

  tasks:
    - name: Test to see if additional control nodes already joined to cluster
      ansible.builtin.command:
        ls /etc/kubernetes
      register: kubedirtest
      failed_when: kubedirtest.rc > 2
      when: hostvars[groups['k8s_master'][0]]['loadbalancer']
      changed_when: false
      tags: cert_key

    - name: Run kubeadm join
      ansible.builtin.command:
        "{{ hostvars[groups['k8s_master'][0]]['kubeadm_join'] }} \
            --control-plane --certificate-key \
            {{ hostvars[groups['k8s_master'][0]]['kubeadm_cert_key'] }}"
      when:
        - "'pki' not in kubedirtest.stdout"
        - hostvars[groups['k8s_master'][0]]['loadbalancer']
      changed_when: true
      tags: cert_key

# ===========================================================================
# Install K8s CNI
# ===========================================================================
- name: Install K8s networking plugin
  hosts: k8s_master
  tags: play_k8s_network

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - jedimt.kubernetes_cni

# ===========================================================================
# Join nodes to Kubernetes cluster
# ===========================================================================
- name: Join Kubernetes nodes to cluster
  hosts: k8s_nodes
  tags: play_k8s_nodes

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - jedimt.kubernetes_join_nodes

# ===========================================================================
# Install MetalLB L2 load balancer
# ===========================================================================
- name: Install MetalLB load balancer
  hosts: k8s_master
  become: true
  tags: play_metallb

  roles:
    - { role: jedimt.kubernetes_metallb,
        # Lenovo range:
        # metallb_start: 10.100.24.48,
        # metallb_end: 10.100.24.52
        # HPE range:
        metallb_start: 10.100.24.85,
        metallb_end: 10.100.24.89
    }

# ===========================================================================
# Install the VMware CSI driver
# ===========================================================================
- name: VMware CSI driver install
  hosts: k8s_master
  become: true
  gather_facts: false
  tags: play_vmware_csi

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - { role: jedimt.vmware_csi,
        # Lenovo Systems:
        # vcenter_ip: "10.100.24.31",
        # vcenter_hostname: "devvcsa.tme.nebulon.com",
        # HPE Systems:
        vcenter_ip: "10.100.24.20",
        vcenter_hostname: "hpevcsa.tme.nebulon.com",
        vcenter_datacenter: "SC0"
    }

# ===========================================================================
# Install Nginx ingress controller
# ===========================================================================
- name: Install nginx ingress controller
  hosts: k8s_master
  become: true
  gather_facts: false
  tags: play_nginx

  roles:
    - jedimt.helm
    - jedimt.kubernetes_nginx_ingress

# ===========================================================================
# Install Kube-Prometheus
# ===========================================================================
- name: Install the Kube-Prometheus project
  hosts: k8s_master
  gather_facts: true
  become: false
  tags: play_prometheus

  roles:
    - jedimt.golang
    - { role: jedimt.kubernetes_kube_prometheus,
        storage_class: "vmw-block-sc"
    }
